### ISSUE TITLE
Reset to defaults by putting applications in alphabetical order?

### ISSUE THREAD

**Issue by danewallace** [blacktop/lporg#15]
Super helpful tool! Question/request: an alternative to the current "default" behavior that would arrange the 1st page of Apple apps in out-of-the-box order while alphabetizing all user-installed apps on subsequent pages.

**Comment by blacktop** [comment]
Thanks! I don't have a lot of time now a days for my older tools sadly, however, the input file is a yaml text file and I bet you could write a tool/script to generate a `launchpad.yml` file that does what you need?  Just FYI, when designing your config yml; macOS doesn't like to have a single app in a folder and will UNDO everything back if that happens.
