### ISSUE TITLE
launchpad DB not found

### ISSUE THREAD

**Issue by LucaMarconato** [blacktop/lporg#19]
Doesn't work for me in Ventura 13.0. If I remember well I had tried it last year in a previous os version (12.x probably) and it didn't work with the same error. Maybe the error it's something specific with my mac (that I keep restoring from machine to machine using Time Machine.

```
macbook@MBP-2021 Desktop % lporg save
? Choose where to save your launch pad settings: home folder
   • SAVING LAUNCHPAD DATABASE
      ⨯ launchpad DB not found    error=stat /0/com.apple.dock.launchpad/db/db: no such file or directory path=/0/com.apple.dock.launchpad/db/db
```

**Comment by blacktop** [comment]
try searching for the folder and let me know if it's in a weird place
