### ISSUE TITLE
Error restoring previous db - OS 13.5.1

### ISSUE THREAD

**Issue by mfleucha** [blacktop/lporg#29]
Hi, I have the following errors come up in verbose mode - restore of an existing db fails. The backup was taken only some 10 weeks ago (around that).

```
(/Users/blacktop/Developer/Github/blacktop/lporg/database/database.go:370)
[2023-08-29 09:25:26]  no such table: widgets

(/Users/blacktop/Developer/Github/blacktop/lporg/database/database.go:370)
[2023-08-29 09:25:26]  [0.22ms]  SELECT * FROM "widgets"
[0 rows affected or returned ]
      ⨯ query all widgets failed  error=no such table: widgets
      • creating App folders and adding apps to them
```

Any help appreciated. 

Thanks, Michael

**Comment by mfleucha** [comment]
Seems to be a duplicate of https://github.com/blacktop/lporg/issues/16

**Comment by blacktop** [comment]
I know that apple removed the old widgets window (but also recently added desktop widgets?) so I think if you remove the widgets section manually from your config it might work?

**Comment by blacktop** [comment]
please try with latest release
