### ISSUE TITLE
New file system in Mojave uses hashes in the DB instead of app names

### ISSUE THREAD

**Issue by charlieporth1** [blacktop/lporg#3]
- [ ] New file system in Mojave uses hashes in the DB instead of app names

**Comment by blacktop** [comment]
I am still seeing app names in mine.  Can you share your dbs?  Maybe they are that way on fresh installs but can still handle the old way for people upgrading?

**Comment by blacktop** [comment]
I'm confused because it looks like you have the same thing that i do in mine.
