### ISSUE TITLE
Not working in 10.15.2 - Widgets Removed

### ISSUE THREAD

**Issue by robertdoleson** [blacktop/lporg#4]
Saving and restoring is not working on 10.15.2. I suspect it's due to the removal of Widgets from Catalina. 

⨯ query all widgets failed  error=no such table: widgets

(no such table: widgets) 
[2019-12-21 06:38:26]  
      • creating Widget folders and adding widgets to them
   ⨯ GetMissing=>Widgets       error=no such table: widgets

**Comment by blacktop** [comment]
I noticed that too, and started on a fix.  I haven't been able to test it thouroly yet.  On my Mac it works, but it seems to "undo" the reorg on a reboot?  There might be other changes to the DB that I need to include?

You can try out the fixes by running what is now in master

**Comment by blacktop** [comment]
pushed a fix hopefully

**Comment by HananoshikaYomaru** [comment]
Actually, this bug happens on MacOS Monterey v12.0.1 too.

**Comment by yokemura** [comment]
Still happens. It gives me `no such table: widgets` error. Monterey 12.2.
