### ISSUE TITLE
Failed to kickstart Dock

### ISSUE THREAD

**Issue by 5ouma** [blacktop/lporg#65]
After updating macOS to Monterey or later, lporg for Dock fails to save Dock Plist. It can't update the Dock or finish correctly.

```
         • importing dock plist
         • restarting com.apple.Dock.agent service
   ⨯ failed to save dock plist: failed to kickstart dock: exit status 1
```

**Comment by blacktop** [comment]
I've also noticed that on Sonoma that the Dock config is no longer being respected and am not sure why?  Have you investigated it at all?

**Comment by 5ouma** [comment]
Like this?
https://github.com/Macjutsu/super/issues/208

**Comment by Ran-Xing** [comment]
@blacktop Lporg Chinese Introduction Video: B23.Tv/3Mjje4V

**Comment by blacktop** [comment]
can you try that last fix to see if it works?

**Comment by 5ouma** [comment]
Thank you!
It fixed!!
