### ISSUE TITLE
Not persisting after logout

### ISSUE THREAD

**Issue by jacobweberbowery** [blacktop/lporg#9]
If I do `lporg load <file>`, it seems to work. But then if I log out and log back in, the icons all move out of their folders. Same if I do `killall Dock` after the load.

This is on Mac OS 12.1 on a 2021 MBP.

The only error I see when running it is "no such table: Widgets".

```
   • PARSE LAUCHPAD DATABASE
      • found launchpad database  database=/var/folders/jd/58cfk_8561n83l5_c51mwc8r0000gn/0/com.apple.dock.launchpad/db/db
         • removed old file          path=/var/folders/jd/58cfk_8561n83l5_c51mwc8r0000gn/0/com.apple.dock.launchpad/db/db
         • removed old file          path=/var/folders/jd/58cfk_8561n83l5_c51mwc8r0000gn/0/com.apple.dock.launchpad/db/db-shm
         • removed old file          path=/var/folders/jd/58cfk_8561n83l5_c51mwc8r0000gn/0/com.apple.dock.launchpad/db/db-wal
      • restarting Dock          
      • clear out groups         
      • disabling SQL update triggers
      • add root and holding pages
      ⨯ query all widgets failed  error=no such table: widgets
      • parsing launchpad config YAML path=launchpad.yml

(/Users/blacktop/Developer/Github/blacktop/lporg/database/database.go:370) 
[2022-01-22 08:12:08]  no such table: widgets 
      • creating App folders and adding apps to them
         • found apps/widgets that are not in supplied config count=12
...
```

**Comment by blacktop** [comment]
I have noticed something similar and I believe it is due to lporg creating folders with a single app inside. MacOS does some kind of validation and if it finds something it doesn't like it undoes lporg or resets the SQLite db somehow. 

For me I ran it and then manually fixed any issues and then re-saved the lporg settings to a file. 

Once there were no longer those single app folder issues it works. 

I tested on macOS 12.1

**Comment by jacobweberbowery** [comment]
I think you're right -- I had one single-app folder. After I removed it, re-saved, and re-loaded, it doesn't seem to be resetting anymore. Thanks!

**Comment by blacktop** [comment]
I'll pin the issue for others until I get around to fixing it so it doesn't create folders with single apps. 👍

**Comment by BullyH** [comment]
Hello,

I am facing the same issue described above. Config: MacBok Pro M1 / 12.3.1

Maybe someone can help me: 

> [...] I had one single-app folder. After I removed it, re-saved, and re-loaded, it doesn't seem to be resetting anymore. Thanks!

1. What is the "single-app folder"?
2. Where can I find "single-app folder"?

It would be great to get further informations about it. Thanks in advance. Best Regards.

**Comment by jacobweberbowery** [comment]
A folder with only one app @BullyH.

**Comment by blacktop** [comment]
if lporg creates either empty Launch Pad folders or folders that only hold a single Application, those are illegal folders and get "corrected" on reboot.  The correction is to undo all the folders.  So what you need to ensure is that you have none of these, and then rerun `lporg save` to get a new good config.  You might also want to run `lporg load` with the new corrected config to make sure it is in the sqlite DBs.  This has worked for me several times (when I've corrected the empty or single app folders)

**Comment by blacktop** [comment]
I added some config validation to check for folders with less that 2 apps in them
